/**
 * UI domain model for cheongyak.com (client- and server-side usage).
 *
 * This module defines the **normalized shapes** that feature code
 * consumes — `Subscription`, `NewsArticle`, `MarketInsight`, and friends.
 * Raw wire responses from the backend live in `./main-api.ts` as DTOs
 * and are folded into these domain types by the feature-local mappers
 * under each feature's `lib/` folder (today: `map-main-api.ts`).
 *
 * When to edit this file:
 * - The UI needs a new field (add to domain type + update mapper).
 * - The UI consolidates or renames something user-visible.
 *
 * Do NOT edit this file when:
 * - The backend changed a raw field name. That belongs in `main-api.ts`;
 *   the mapper absorbs the rename so domain types stay stable.
 */
import { z } from 'zod';

// ============================================================
// Status
// ============================================================

export const SubscriptionStatusSchema = z.enum([
  'upcoming',
  'accepting',
  'pending',
  'result_today',
  'closed',
]);
export type SubscriptionStatus = z.infer<typeof SubscriptionStatusSchema>;

export const SubscriptionTypeSchema = z.enum(['public', 'private']);
export type SubscriptionType = z.infer<typeof SubscriptionTypeSchema>;

export const NewsCategorySchema = z.enum([
  'all',
  'policy',
  'market',
  'analysis',
  'notice',
]);
export type NewsCategory = z.infer<typeof NewsCategorySchema>;

// ============================================================
// Subscription
// ============================================================

export const SubscriptionSchema = z.object({
  id: z.string(),
  name: z.string(),
  location: z.object({
    sido: z.string(),
    gugun: z.string(),
    dong: z.string().optional(),
  }),
  builder: z.string(),
  status: SubscriptionStatusSchema,
  type: SubscriptionTypeSchema,
  applicationStart: z.string(),
  applicationEnd: z.string(),
  totalUnits: z.number(),
  sizeRange: z.string(),
  priceRange: z.string().optional(),
  viewCount: z.number().optional(),
});
export type Subscription = z.infer<typeof SubscriptionSchema>;

export const SchedulePhaseSchema = z.object({
  phase: z.string(),
  label: z.string(),
  startDate: z.string(),
  endDate: z.string().optional(),
  state: z.enum(['past', 'current', 'future']),
});
export type SchedulePhase = z.infer<typeof SchedulePhaseSchema>;

// 활성 규제 플래그 키 (백엔드 RegulationSection boolean 필드명과 동일)
export const RegulationFlagSchema = z.enum([
  'speculativeArea',
  'adjustmentArea',
  'priceCeiling',
  'redevelopment',
  'publicHousingDistrict',
  'largeScaleDevelopment',
  'metropolitanPublicHousing',
  'publicHousingSpecialLaw',
]);
export type RegulationFlag = z.infer<typeof RegulationFlagSchema>;

// 특공 세분 유형 — SpecialDetailSection 의 non-null 필드를 한국어 라벨로 집약
export const SpecialSupplyBreakdownItemSchema = z.object({
  category: z.string(), // 예: '신혼부부', '다자녀'
  count: z.number(),
});
export type SpecialSupplyBreakdownItem = z.infer<
  typeof SpecialSupplyBreakdownItemSchema
>;

export const ModelSupplySchema = z.object({
  modelNo: z.string(),
  houseType: z.string().optional(),
  supplyArea: z.number().optional(),
  generalCount: z.number(),
  specialCount: z.number(),
  specialBreakdown: z.array(SpecialSupplyBreakdownItemSchema),
  /** 만원 단위 — UI 표시는 formatter 통과 */
  topAmount: z.number().optional(),
});
export type ModelSupply = z.infer<typeof ModelSupplySchema>;

export const CompetitionRowSchema = z.object({
  houseType: z.string(),
  rank: z.number().optional(),
  residence: z.string().optional(),
  supplyCount: z.number().optional(),
  requestCount: z.number().optional(),
  /** "15.00" | "(N세대 부족)" | "미달" | undefined(집계 전) */
  rateDisplay: z.string().optional(),
  isShortage: z.boolean(),
});
export type CompetitionRow = z.infer<typeof CompetitionRowSchema>;

export const WinnerScoreRowSchema = z.object({
  houseType: z.string(),
  residence: z.string().optional(),
  lowestDisplay: z.string(),
  highestDisplay: z.string(),
  averageDisplay: z.string(),
});
export type WinnerScoreRow = z.infer<typeof WinnerScoreRowSchema>;

export const SpecialSupplyStatusRowSchema = z.object({
  houseType: z.string(),
  /** 8종 고정 카테고리 한국어 원문 */
  categoryName: z.string(),
  supplyCount: z.number().optional(),
  localAreaCount: z.number().optional(),
  metropolitanCount: z.number().optional(),
  otherAreaCount: z.number().optional(),
  totalCount: z.number().optional(),
});
export type SpecialSupplyStatusRow = z.infer<
  typeof SpecialSupplyStatusRowSchema
>;

export const SubscriptionDetailSchema = SubscriptionSchema.extend({
  // 공식 링크
  builderUrl: z.string().optional(),
  announcementUrl: z.string().optional(),
  applyHomeUrl: z.string().optional(),
  // 부가 정보
  supplyAddress: z.string().optional(),
  businessEntityName: z.string().optional(),
  inquiryPhone: z.string().optional(),
  /** yyyy-MM */
  moveInMonth: z.string().optional(),
  // 섹션 데이터
  schedule: z.array(SchedulePhaseSchema),
  regulations: z.array(RegulationFlagSchema),
  models: z.array(ModelSupplySchema),
  competitions: z.array(CompetitionRowSchema),
  winnerScores: z.array(WinnerScoreRowSchema),
  specialSupplyStatus: z.array(SpecialSupplyStatusRowSchema),
});
export type SubscriptionDetail = z.infer<typeof SubscriptionDetailSchema>;

// ============================================================
// News
// ============================================================

export const NewsArticleSchema = z.object({
  id: z.string(),
  title: z.string(),
  excerpt: z.string(),
  body: z.string().optional(),
  category: NewsCategorySchema,
  thumbnailUrl: z.string().optional(),
  publishedAt: z.string(),
  relatedSubscriptionIds: z.array(z.string()).optional(),
});
export type NewsArticle = z.infer<typeof NewsArticleSchema>;

// ============================================================
// Market Insights
// ============================================================

export const MarketInsightSchema = z.object({
  label: z.string(),
  value: z.string(),
  /** 데이터가 실제로 올라갔는지/내려갔는지 — 아이콘 방향에만 사용 */
  trend: z.enum(['up', 'down', 'flat']),
  trendValue: z.string(),
});
export type MarketInsight = z.infer<typeof MarketInsightSchema>;

// ============================================================
// Top Trades (실거래가)
// ============================================================

export const TopTradeSchema = z.object({
  id: z.string(),
  aptName: z.string(),
  /** "서초구 반포동" 형태로 합쳐진 지역 — API 가 sidoName 을 내리지 않아 시도는 생략 */
  region: z.string(),
  /** "85㎡ (34평)" 형태. 면적이 없으면 undefined */
  area: z.string().optional(),
  floor: z.number().optional(),
  /** "42억 3,000만" 형태 */
  dealAmount: z.string(),
  /** yyyy-MM-dd */
  dealDate: z.string(),
});
export type TopTrade = z.infer<typeof TopTradeSchema>;

// ============================================================
// Filter Options
// ============================================================

export const RegionSchema = z.object({
  sido: z.string(),
  guguns: z.array(z.string()),
});
export type Region = z.infer<typeof RegionSchema>;

export const FilterOptionsSchema = z.object({
  regions: z.array(RegionSchema),
  builders: z.array(z.string()),
});
export type FilterOptions = z.infer<typeof FilterOptionsSchema>;

// ============================================================
// Paginated Response
// ============================================================

export const PaginatedResponseSchema = <T extends z.ZodTypeAny>(itemSchema: T) =>
  z.object({
    items: z.array(itemSchema),
    total: z.number(),
    page: z.number(),
    totalPages: z.number(),
  });

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  totalPages: number;
}
